version: '3'
services:

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  tripmanagementquery:
    build: ../trip-management-query
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo
      - discoveryservice

  tripmanagementcmd:
    build: ./
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo
      - discoveryservice

  discoveryservice:
    image: aista/eureka
    ports:
      - "8761:8761"

  gmapsadapter:
    build: ../gmaps-adapter/
    environment:
      - EUREKA_SERVER=discoveryservice
    ports:
      - '8080'
    depends_on:
      - discoveryservice
      - rabbitmq

  calculationservice:
    image: aista/calculation-service:local
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice
    ports:
      - '8080'
    depends_on:
      - gmapsadapter
      - discoveryservice
      - rabbitmq


volumes:
  mongo: