version: '3'
services:

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  tripmanagementquery:
    image: aista/trip-management-query
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo
      - discovery-service

  tripmanagementcmd:
    build: ./
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '8080'
    depends_on:
      - rabbitmq
      - mongo
      - tripmanagementquery
      - discovery-service
      - calculationservice
      - driverquery
      - drivercmd

  discovery-service:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    container_name: eureka-server

  gmapsadapter:
    image: aista/gmaps-adapter
    environment:
      - EUREKA_SERVER=discovery-service
    ports:
      - '8080'
    depends_on:
      - discovery-service

  calculationservice:
    image: aista/calculation-service
    environment:
      - EUREKA_SERVER=discovery-service
    ports:
      - '8080'
    depends_on:
      - gmapsadapter
      - discovery-service

  driverquery:
    build: aista/driver-query
    container_name: 'driverquery'
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo

  drivercmd:
    build: aista/driver-cmd
    container_name: 'drivercmd'
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongo: