management.endpoints.web.exposure.include: "*"

---

spring:
  profiles: dev
  data:
    mongodb:
      database: trip-management-cmd
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

aist:
  use_ssl: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8080/eureka/

server:
  port: ${APP_PORT:8080}

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/trip-management-cmd
          aggregates:
            - Trip

amqp:
  events:
    host: ${RABBIT_HOST:localhost}
    exchange-name: eventBus
    queue-name: eventQueue
    handlers: org.aistesting.microservices.tripmanagement.cmd.domain.eventhandlers

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG

---

spring:
  profiles: test

eureka:
  client:
    enabled: false
    
---

spring:
  profiles: local
  data:
    mongodb:
      database: trip-management-cmd
      host: ${DOCKER_MACHINE_IP:localhost}
      port: ${MONGO_PORT:27017}
  application:
    name: tripmanagementcmd
  rabbitmq:
    host: ${DOCKER_MACHINE_IP:localhost}

aist:
  use_ssl: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_MACHINE_IP:localhost}:8761/eureka/

server:
  port: ${APP_PORT:8093}

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${DOCKER_MACHINE_IP:localhost}:${MONGO_PORT:27017}/trip-management-cmd
          aggregates:
            - Trip

amqp:
  events:
    host: ${DOCKER_MACHINE_IP:localhost}
    exchange-name: eventBus
    queue-name: eventQueue
    handlers: org.aistesting.microservices.tripmanagement.cmd.domain.eventhandlers

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
    