# Mongo config
spring:
  data:
    mongodb:
      database: trip-management-cmd
      host: localhost
      port: 27017
      username:
      password:
  application:
    name: trip-management-cmd
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/trip-management-cmd
          aggregates:
            - TripAggregate

amqp:
    events:
      host: localhost
      exchange-name: eventBus-tripcmd
      queue-name: eventQueue-tripcmd
      handlers:
